spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dealer_db
    username: root
    password: LuhaismyMan12
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
token:
  signing:
    #This key is used as base to generate tokens for authentication
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351